export const styles = {
  cardStyle: { width: "18rem", height: "17rem" },
  ImageCardStyle: {
    cursor: "pointer",
    borderRadius: "26px",
    height: "18rem",
    objectFit: "cover",
  },
  loaderStyle: {
    marginLeft: "42vw",
    marginTop: "33vh",
    fontSize: "156px",
  },
  mobileFadeStyleOff: {
    width: "12rem",
    height: "3rem",
    backgroundColor: "#949494",
    border: "none",
    fontSize: "1.3rem",
    outline: "none",
  },
  mobileFadeStyleOn: {
    width: "12rem",
    height: "3rem",
    backgroundColor: "#BAB6B6",
    border: "none",
    fontSize: "1.3rem",
    outline: "none",
  },
  fullWidthHeightStyle: { height: "100%", width: "100%" },
  mobileDivStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  mobileButtonStyle: {
    width: "12.5rem",
    margin: "3rem",
    flexShrink: "2",
  },
  mobileRowContainerStyle: {
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
    margin: "0rem",
  },
  mobileCardStyle: {
    width: "24rem",
    border: "none",
  },
  mobileCardImgOverlayStyle: {
    height: "7rem",
    marginLeft: "0.05rem",
    width: "22rem",
    color: "#fff",
    opacity: "0.8",
    marginTop: "8rem",
    borderBottomLeftRadius: "15px",
    borderBottomRightRadius: "15px",
    backgroundColor: "black",
    position: "relative",
    zIndex: "2",
  },
  mobileCardTitleStyle: {
    textTransform: "uppercase",
    lineHeight: "2rem",
  },
  mobileCardImgStyle: {
    cursor: "pointer",
    objectFit: "cover",
    margin: ".05rem",
    height: "15rem",
    borderRadius: "12px",
    zIndex: "1",
    position: "relative",
  },
  showMoreButtonStyle: {
    paddingRight: "1rem",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  //   foodItemCardDeckStyle: {
  //     display: "flex",
  //     flexWrap: "wrap",
  //     flexDirection: "row",
  //   },
  //   foodItemCardStyle: {
  //     width: "19rem",
  //     margin: "0.5rem",
  //     border: "none",
  //   },
  //   emojiStyle: {
  //     color: "#000",
  //     cursor: "pointer",
  //   },
  //   foodItemCardImageStyle: {
  //     cursor: "pointer",
  //     borderRadius: "26px",
  //     height: "17.5rem",
  //     objectFit: "cover",
  //   },
  //   foodImgOverlayStyle: { color: "#fff", width: "100%" },
  //   foodItemCardOverlayStyle: {
  //     width: "",
  //     marginTop: "10rem",
  //     position: "relative",
  //     backgroundColor: "black",
  //   },
};
