import Pic from "../Images/markx.png";
export const FoodData = [
  {
    id: "1",
    item: "item01",
    ingredient: "potatos,cocumber",
    available: true,
    country: "Finland",
    discount: "FI",
    image: Pic,
    foodChoices: ["Non-Veg"],
  },
  {
    id: "2",
    item: "item02",
    ingredient: "garlic,Lamb,salad",

    available: true,
    country: "Finland",
    discount: "FI",
    image: Pic,

    foodChoices: ["Non-Veg"],
  },
  {
    id: "3",
    item: "item03",
    ingredient: "garlic, salad, Chilli ",
    available: true,
    country: "Finland",
    discount: "FI",
    image: Pic,
    foodChoices: ["Veg"],
  },
  {
    id: "4",
    item: "item04",
    ingredient: "garlic, salad, Chicken, Chilli",
    available: true,
    country: "Finland",
    discount: "FI",
    image: Pic,
    foodChoices: ["Lacto Veg"],
  },
  {
    id: "5",
    item: "item05",
    ingredient: "garlic, salad, Chicken,Chilli",
    available: true,
    country: "Finland",
    discount: "FI",
    image: Pic,
    foodChoices: ["Non-Veg"],
  },
  {
    id: "6",
    item: "item06",
    ingredient: "garlic, salad, Chicken, Chilli",
    available: true,
    country: "Finland",
    discount: "FI",
    image: Pic,
    foodChoices: ["Lactose Free"],
  },
  {
    id: "7",
    item: "item07",
    ingredient: "garlic, salad, Chicken, Chilli",
    available: true,
    country: "Finland",
    discount: "FI",
    image: "",
    foodChoices: ["Gluton free"],
  },
  {
    id: "8",
    item: "item08",
    ingredient: "garlic, salad, Chicken, Chilli",
    available: true,
    country: "Finland",
    discount: "FI",
    image: "",
    foodChoices: ["Gluton free"],
  },
  /*   {
    id: "9",
    item: "item09",
    available: "25.6550",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "10",
    item: "item10",
    available: "26.7042",
    country: "Finland",
    discount: "FI",
  }, */
  /* {
    id: "11",
    item: "item11",
    available: "21.7972",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "12",
    item: "item12",
    available: "29.7639",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "13",
    item: "item13",
    available: "28.1861",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "14",
    item: "item14",
    available: "24.4414",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "15",
    item: "item15",
    available: "21.6167",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "16",
    item: "item16",
    available: "25.7285",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "17",
    item: "item17",
    available: "22.8403",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "18",
    item: "item18",
    available: "27.2736",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "19",
    item: "item19",
    available: "26.9458",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "20",
    item: "item20",
    available: "23.1331",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "21",
    item: "item21",
    available: "25.6639",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "22",
    item: "item22",
    available: "23.1320",
    country: "Finland",
    discount: "FI",
  },

  {
    id: "23",
    item: "item23",
    available: "26.7097",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "24",
    item: "item24",
    available: "25.5472",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "25",
    item: "item25",
    available: "19.9862",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "26",
    item: "item26",
    available: "22.7917",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "27",
    item: "item27",
    available: "23.6999",
    country: "Finland",
    discount: "FI",
  },
  {
    id: "28",
    item: "item28",
    available: "22.7500",
    country: "Finland",
    discount: "FI",
  },*/
];
